/**
 * Ethereum HTLC client for AgentSwap.
 *
 * Wraps ethers v6 calls to the HashedTimelockETH contract.
 * All amounts are in wei (bigint) — no floating point.
 */

import { ethers } from "ethers";
import type { HTLCReceipt, Preimage } from "@agentswap/shared";

// ── ABI (minimal — only the functions we call) ───────────────────────────────
// Full ABI is generated by Hardhat; we inline the fragments we need so the
// client package can be used without a compile step in development.

export const HTLC_ABI = [
  "function lock(bytes32 swapId, address payable recipient, bytes32 hashlock, uint256 expiry) payable",
  "function claim(bytes32 swapId, bytes32 preimage)",
  "function refund(bytes32 swapId)",
  "function getSwap(bytes32 swapId) view returns (tuple(address sender, address recipient, uint256 amount, bytes32 hashlock, uint256 expiry, bool claimed, bool refunded, bytes32 preimage))",
  "event Locked(bytes32 indexed swapId, address indexed sender, address indexed recipient, uint256 amount, bytes32 hashlock, uint256 expiry)",
  "event Claimed(bytes32 indexed swapId, bytes32 preimage)",
  "event Refunded(bytes32 indexed swapId)",
] as const;

// ── Preimage helpers ─────────────────────────────────────────────────────────

/**
 * Hash a preimage using keccak256(abi.encode(bytes32)) — matches the Solidity contract.
 * Uses ethers.getBytes for safe hex→bytes conversion (no BigInt overflow on leading zeros).
 */
export function keccakPreimage(preimageHex: Preimage): string {
  // Normalise to 32 bytes (pad left with zeros if shorter — shouldn't happen with generatePreimage)
  const hex = preimageHex.startsWith("0x") ? preimageHex : "0x" + preimageHex;
  const padded = ethers.zeroPadValue(hex, 32); // always returns 0x-prefixed 32-byte hex
  return ethers.keccak256(
    ethers.AbiCoder.defaultAbiCoder().encode(["bytes32"], [padded])
  );
}

// ── Client class ─────────────────────────────────────────────────────────────

export interface EthHTLCClientConfig {
  rpcUrl: string;
  /** Private key of the signing account (0x-prefixed) */
  privateKey: string;
  /** Deployed HashedTimelockETH contract address */
  contractAddress: string;
}

export class EthHTLCClient {
  public readonly provider: ethers.JsonRpcProvider;
  public readonly signer: ethers.Wallet;
  public readonly contract: ethers.Contract;

  constructor(config: EthHTLCClientConfig) {
    this.provider = new ethers.JsonRpcProvider(config.rpcUrl);
    this.signer = new ethers.Wallet(config.privateKey, this.provider);
    this.contract = new ethers.Contract(config.contractAddress, HTLC_ABI, this.signer);
  }

  // ── Lock ───────────────────────────────────────────────────────────────────

  /**
   * Lock ETH in the HTLC contract.
   * The seller calls this to commit their ETH side of the atomic swap.
   */
  async lock(params: {
    /** UUID encoded as bytes32 (use uuidToBytes32 helper) */
    swapId: string;
    recipient: string;
    preimage: Preimage;
    /** Amount in wei */
    amountWei: bigint;
    timelockHours: number;
  }): Promise<HTLCReceipt> {
    const hashlock = keccakPreimage(params.preimage);
    const expiry = BigInt(Math.floor(Date.now() / 1000) + params.timelockHours * 3600);

    const tx: ethers.TransactionResponse = await this.contract.lock(
      params.swapId,
      params.recipient,
      hashlock,
      expiry,
      { value: params.amountWei }
    );

    const receipt = await tx.wait(1); // wait for 1 confirmation
    if (!receipt) throw new Error("ETH lock transaction failed");

    return {
      chain: "eth",
      txId: receipt.hash,
      lockTime: Number(expiry),
      amount: params.amountWei.toString(),
      preimageHash: hashlock,
      contractAddress: await this.contract.getAddress(),
    };
  }

  // ── Claim ──────────────────────────────────────────────────────────────────

  /**
   * Claim the locked ETH by revealing the preimage.
   * Called by the recipient (buyer in ETH-side terminology) after arbitrator approval.
   */
  async claim(swapId: string, preimage: Preimage): Promise<string> {
    const hex = preimage.startsWith("0x") ? preimage : "0x" + preimage;
    const padded = ethers.zeroPadValue(hex, 32); // 0x-prefixed 32-byte hex
    const tx: ethers.TransactionResponse = await this.contract.claim(swapId, padded);
    const receipt = await tx.wait(1);
    if (!receipt) throw new Error("ETH claim transaction failed");
    return receipt.hash;
  }

  // ── Refund ─────────────────────────────────────────────────────────────────

  async refund(swapId: string): Promise<string> {
    const tx: ethers.TransactionResponse = await this.contract.refund(swapId);
    const receipt = await tx.wait(1);
    if (!receipt) throw new Error("ETH refund transaction failed");
    return receipt.hash;
  }

  // ── Query ──────────────────────────────────────────────────────────────────

  async getSwap(swapId: string): Promise<{
    sender: string;
    recipient: string;
    amount: bigint;
    hashlock: string;
    expiry: bigint;
    claimed: boolean;
    refunded: boolean;
    preimage: string;
  }> {
    return this.contract.getSwap(swapId);
  }

  async getBalance(address: string): Promise<bigint> {
    return this.provider.getBalance(address);
  }
}

// ── Utility ──────────────────────────────────────────────────────────────────

/**
 * Encode a UUID string to a deterministic bytes32 value.
 * UUIDs are 128 bits; we left-pad to 32 bytes.
 */
export function uuidToBytes32(uuid: string): string {
  const hex = uuid.replace(/-/g, "");
  return "0x" + hex.padStart(64, "0");
}
