/**
 * @agentswap/shared/types
 *
 * Single source of truth for all cross-package types.
 * Both the on-chain packages and the agent/dashboard packages import from here.
 * Keep this file free of runtime dependencies — pure TypeScript types only.
 */

// ── Primitive aliases ────────────────────────────────────────────────────────

/** Hex-encoded SHA-256 hash (64 hex chars), used as the HTLC payment hash */
export type PreimageHash = string;

/** Hex-encoded 32-byte random secret; revealed at settlement to claim funds */
export type Preimage = string;

/** Hex string (0x-prefixed or bare) transaction / payment identifier */
export type TxId = string;

// ── Swap Proposal ────────────────────────────────────────────────────────────

/**
 * The canonical offer structure exchanged during agent negotiation.
 * Created by the buyer agent, countered/accepted by the seller agent.
 */
export interface SwapProposal {
  /** UUIDv4 — unique across all swaps in a session */
  id: string;

  /**
   * Natural-language description of the off-chain deliverable being purchased.
   * The arbitrator agent uses this to evaluate settlement.
   * Example: "Translate the attached document to French, 500 words max."
   */
  taskDescription: string;

  /** Amount the buyer locks on the Lightning/Bitcoin side (satoshis) */
  btcAmountSats: bigint;

  /** Amount the seller locks on the Ethereum side (wei) */
  ethAmountWei: bigint;

  /**
   * Bitcoin HTLC expiry expressed in hours from lock time.
   * BTC timelock must be LONGER than ETH so the seller can always claim
   * on ETH first and then reveal the preimage for BTC.
   */
  timelock_btc_hours: number;

  /** Ethereum HTLC expiry in hours from lock time (must be < timelock_btc_hours) */
  timelock_eth_hours: number;

  /**
   * SHA-256(preimage) — generated by the buyer, committed in both HTLCs.
   * The preimage is kept secret until the arbitrator approves settlement.
   */
  preimageHash: PreimageHash;

  /** ISO 8601 timestamp when this proposal was first created */
  createdAt: string;

  /** ISO 8601 timestamp of the last counter-offer edit */
  updatedAt: string;
}

// ── Swap State Machine ───────────────────────────────────────────────────────

/**
 * State machine for a single atomic swap lifecycle.
 *
 *   NEGOTIATING → LOCKED → EVALUATING → APPROVED → SETTLED
 *                    ↓                               ↓
 *                 REFUNDED ←──────────────── (timeout)
 */
export enum SwapState {
  /** Agents are exchanging counter-offers; no funds committed yet */
  NEGOTIATING = "NEGOTIATING",

  /** Both HTLCs are confirmed on-chain; funds are escrowed */
  LOCKED = "LOCKED",

  /**
   * Seller has submitted the completed deliverable;
   * arbitrator agent is reviewing it against taskDescription
   */
  EVALUATING = "EVALUATING",

  /** Arbitrator approved the deliverable; preimage can be revealed */
  APPROVED = "APPROVED",

  /** Preimage revealed; both HTLCs claimed; swap complete */
  SETTLED = "SETTLED",

  /** One or both timelocks expired; funds returned to senders */
  REFUNDED = "REFUNDED",
}

// ── Agent Messages ───────────────────────────────────────────────────────────

export type AgentRole = "buyer" | "seller" | "arbitrator";

/**
 * A single message in the multi-agent negotiation log.
 * Stored in order and replayed in the dashboard feed.
 */
export interface AgentMessage {
  /** Which agent produced this message */
  role: AgentRole;

  /** Free-form natural language content (proposal JSON may be embedded) */
  content: string;

  /** ISO 8601 timestamp */
  timestamp: string;

  /** Links the message back to its SwapProposal.id */
  swapId: string;

  /**
   * Optional structured payload — e.g. a counter-offer proposal or
   * an arbitrator verdict. Agents should check this before parsing `content`.
   */
  payload?: SwapProposal | ArbitratorVerdict | Record<string, unknown>;
}

// ── Arbitrator Verdict ───────────────────────────────────────────────────────

/**
 * Structured output from the arbitrator agent after evaluating the deliverable.
 * Drives the EVALUATING → APPROVED | REFUNDED transition.
 */
export interface ArbitratorVerdict {
  swapId: string;
  approved: boolean;
  /** Score 0–100 measuring deliverable quality vs taskDescription */
  qualityScore: number;
  /** Human-readable reasoning — shown in the dashboard */
  reasoning: string;
  /** If approved, arbitrator releases the preimage to trigger settlement */
  preimage?: Preimage;
  timestamp: string;
}

// ── HTLC Receipts ────────────────────────────────────────────────────────────

/**
 * On-chain confirmation receipt for a locked HTLC.
 * Emitted by both the Lightning package and the Ethereum package.
 */
export interface HTLCReceipt {
  /** Which chain the HTLC lives on */
  chain: "btc" | "eth";

  /**
   * BTC: payment hash (Lightning invoice hash) or on-chain txid
   * ETH: contract deployment txHash or lock() call txHash
   */
  txId: TxId;

  /** Unix timestamp (seconds) when the HTLC expires */
  lockTime: number;

  /**
   * BTC: amount in satoshis (stored as string to avoid JS precision loss)
   * ETH: amount in wei   (stored as string for the same reason)
   */
  amount: string;

  preimageHash: PreimageHash;

  /** Ethereum HTLC contract address (eth only) */
  contractAddress?: string;

  /** Lightning payment request / Bolt11 invoice (btc only) */
  invoice?: string;
}

// ── Full Swap Record ─────────────────────────────────────────────────────────

/**
 * Aggregate record that ties together all swap artefacts.
 * Persisted in the dashboard's in-memory store and streamed via SSE.
 */
export interface SwapRecord {
  proposal: SwapProposal;
  state: SwapState;
  messages: AgentMessage[];
  btcReceipt?: HTLCReceipt;
  ethReceipt?: HTLCReceipt;
  verdict?: ArbitratorVerdict;
  /** Unix ms timestamp when final state (SETTLED | REFUNDED) was reached */
  settledAt?: number;
}

// ── Environment Config ───────────────────────────────────────────────────────

/** Typed shape of the loaded .env — validated at startup in each package */
export interface AppConfig {
  BUYER_LND_REST_URL: string;
  SELLER_LND_REST_URL: string;
  BUYER_LND_TLS_CERT_PATH: string;
  SELLER_LND_TLS_CERT_PATH: string;
  ETH_RPC_URL: string;
  ETH_BUYER_PRIVATE_KEY: string;
  ETH_SELLER_PRIVATE_KEY: string;
  ETH_HTLC_CONTRACT_ADDRESS: string;
  ANTHROPIC_API_KEY: string;
  AGENT_MODEL: string;
}
