/**
 * packages/agents/src/types.ts
 *
 * Coordinator-internal types.
 *
 * WHY a separate SwapRecord here?
 * ─────────────────────────────────────────────────────────────────────────────
 * The shared `SwapRecord` (packages/shared/types.ts) is the *public* record —
 * streamed to the dashboard over SSE and safe to serialize. It deliberately
 * does NOT carry the secret preimage.
 *
 * `CoordinatorSwapRecord` is the *internal* record held by the SwapCoordinator.
 * It adds the preimage (secret), the ETH lockId, the BTC rHash, and other
 * coordinator-specific fields. It must NEVER be serialized and sent over the
 * network.
 */

import type { SwapProposal, SwapState, HTLCReceipt } from "@agentswap/shared";

// ── HTLCClient interface ─────────────────────────────────────────────────────

/**
 * Structural interface for the Ethereum HTLC client used by SwapCoordinator.
 *
 * `AgentSwapHTLCClient` (packages/ethereum) satisfies this interface.
 * Defined as a structural type so the coordinator can be tested with a mock.
 *
 * The coordinator uses two operations:
 *   - createLock  — buyer locks ETH with the shared preimageHash
 *   - refund      — buyer reclaims ETH after timelock expires on the refund path
 */
export interface HTLCClient {
  createLock(params: {
    /** SHA-256(preimage) as a 0x-prefixed 32-byte hex string */
    preimageHash: string;
    /** Ethereum address of the seller — will call claim() to receive ETH */
    seller: string;
    /** Hours until the lock expires */
    timelockHours: number;
    /** ETH amount in wei */
    amountWei: bigint;
  }): Promise<{
    /** bytes32 lock identifier, emitted by the LockCreated event */
    lockId: string;
    /** Full HTLCReceipt for persisting in the swap record */
    receipt: HTLCReceipt;
  }>;

  /**
   * Reclaim locked ETH. May only succeed after the timelock has expired.
   * Returns the transaction hash.
   */
  refund(lockId: string): Promise<string>;
}

// ── Coordinator config ───────────────────────────────────────────────────────

/**
 * Optional second-argument config for SwapCoordinator.
 * All values fall back to environment variables when omitted.
 */
export interface SwapCoordinatorConfig {
  /**
   * Ethereum address of the seller.  Used as the `seller` arg in createLock.
   * Defaults to process.env.ETH_SELLER_ADDRESS.
   */
  sellerEthAddress?: string;

  /**
   * Claude model to use for arbitration.
   * Defaults to process.env.AGENT_MODEL or "claude-sonnet-4-6".
   */
  agentModel?: string;
}

// ── Coordinator-internal SwapRecord ─────────────────────────────────────────

/**
 * Full internal state for a single swap managed by SwapCoordinator.
 *
 * ⚠️  SECURITY: The `preimage` field is the secret that unlocks BOTH chains.
 *   - Never log it.
 *   - Never include it in any SSE/HTTP response.
 *   - Only pass it to `lndClient.settleInvoice` on the approved path.
 */
export interface CoordinatorSwapRecord {
  /** Same as proposal.id — used as the primary key in SwapStore. */
  id: string;

  /**
   * The agreed swap terms. Note: after initiateSwap() this copy has the
   * coordinator-generated preimageHash, which may differ from the value the
   * buyer agent placed in the original proposal.
   */
  proposal: SwapProposal;

  /** Current lifecycle state. */
  state: SwapState;

  /**
   * 32-byte random secret generated by the coordinator.
   * Revealed on the Lightning side only after arbitrator approval.
   * ⚠️  DO NOT SERIALIZE.
   */
  preimage?: Buffer;

  /**
   * SHA-256(preimage) as a hex string (64 chars, no 0x prefix).
   * Committed to both the ETH HTLC and the Lightning HODL invoice.
   */
  preimageHash: string;

  /**
   * bytes32 lockId returned by AgentSwapHTLC.createLock().
   * Required to call refund() on the ETH side.
   */
  ethLockId?: string;

  /** Full ETH HTLC receipt for dashboard display. */
  ethReceipt?: HTLCReceipt;

  /**
   * Lightning payment hash (hex, 64 chars) returned by createHodlInvoice().
   * Required to call cancelInvoice() on the BTC side.
   */
  btcRHash?: string;

  /** BOLT-11 payment request — shown to buyer so they can pay. */
  btcPaymentRequest?: string;

  /** Full BTC HTLC receipt for dashboard display. */
  btcReceipt?: HTLCReceipt;

  /** Unix-ms timestamp of record creation. */
  createdAt: number;

  /** Set when state transitions to SETTLED. Unix-ms. */
  settledAt?: number;

  /** Set when state transitions to REFUNDED. Unix-ms. */
  refundedAt?: number;

  /** The seller's work product, stored after submitDeliverable(). */
  deliverable?: string;

  /** Arbitrator's reasoning string from the ArbitratorVerdict. */
  arbitratorReasoning?: string;

  /** Arbitrator quality score 0–100. */
  qualityScore?: number;
}

// ── Safe public projection ───────────────────────────────────────────────────

/**
 * Sanitised version of CoordinatorSwapRecord safe for external consumers
 * (dashboard, SSE stream, logs).
 *
 * The `preimage` field is intentionally omitted.
 */
export type PublicSwapRecord = Omit<CoordinatorSwapRecord, "preimage">;
